version: '3'

services:
  postgres:
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=booksdb
      - TZ=UTC
    ports:
      - "5433:5432"