name: Release

on:
  push:
    branches: [ "Main" ]
  pull_request:
    branches: [ "Main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13-alpine
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: booksdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Generate jooq
        run: |
          export PGUSER=user
          export PGPASSWORD=password
          export DATABASE_URL=jdbc:postgresql://localhost:5432/booksdb
          ./gradlew generateJooq

      - name: Run tests
        run: |
          export PGUSER=user
          export PGPASSWORD=password
          export DATABASE_URL=jdbc:postgresql://localhost:5432/booksdb
          ./gradlew test

      - name: Build code
        run: |
          ./gradlew build -x test

      - name: Stop any gradle daemons
        run: ./gradlew -stop

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: books-ktor-api.jar
          path: ./build/libs/
          retention-days: 1

  push-jar-file:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: success() && github.ref == 'refs/heads/Main'

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: books-ktor-api.jar
          path: ./build/libs/

      - name: Move jar file
        run: mv ./build/libs/books-ktor-api.jar .

      - name: Git push
        run: |
          git config --global user.name 'Github Action'
          git config --global user.email 'action@github.com'
          git add books-ktor-api.jar
          git commit -m "🚚 | Push jar file️"
          git push origin Main

  deploy:
    runs-on: ubuntu-latest
    needs: push-jar-file
    if: success() && github.ref == 'refs/heads/Main'

    steps:
      - uses: actions/checkout@v3

      - name: Use Node 18
        uses: actions/setup-node@v1
        with:
          node-version: 18.x

      - name: Install Railway
        run: npm i -g @railway/cli

      - name: Deploy
        run: railway up
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}